name: Deploy Flutter Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./note_book_app
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: ./note_book_app/pubspec.yaml
          channel: stable

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./note_book_app/build/web
